### ISSUE TITLE
Can this component be used as a recyclerview item?

### ISSUE THREAD

**Issue by jayeshbabuav** [fabiosassu/StackExpandableView#11]
I am getting this behaviour where when the item goes out of the screen, and comes back, the stacked cards are no longer appear as a stacked.  https://drive.google.com/file/d/1MEbMvQXRn9jDNTpbDgzQFtBF78LyczrL/view?usp=sharing

**Comment by adhikaputraa** [comment]
got this issue as well, @jayeshbabuav have you found the solution?
