### ISSUE TITLE
View stack looks off when the content is huge in second or third card 

### ISSUE THREAD

**Issue by skybind2020** [fabiosassu/StackExpandableView#8]
<img width="364" alt="Screen Shot 2021-12-03 at 12 11 17 AM" src="https://user-images.githubusercontent.com/93882119/144554612-a7b15746-d507-4148-b324-0fe565032b19.png">

**Comment by fabiosassu** [comment]
I've fixed the issue and published the 1.0.2 update. Let me know if it fixes the issue for you!
